### PR TITLE
GitMerge: alias for merging git branches

### PR DESCRIPTION
**Pull request by MSadir**
Added shortcut to do non-fastforward merge requests.

### CODE REVIEW

**Comment by AdamWhittingham** [comment]
Hey Morgan, hope you're well!

I can see how useful this is but I'm not crazy keen on this alias. The name implies its for merging branches and (whilst it does), the dependency on passing `rake` and the deletion of remote branches mean that it could be a nasty surprise for someone.

It is very useful to merge `--no-ff` & delete remote branches though- would these be useful as separate git aliases in the main config, and then your ruby-merge-and-delete-branches could live in a local extension?

**Comment by MSadir** [comment]
Hey Adam, yeah that is more than fine I just thought so long as I was playing with your config I may as well pull request it. I can see you have referenced the pull request in a commit so I will close this. Hope things are going well on your end too.

**Comment by AdamWhittingham** [comment]
All good thanks :+1: 

Just wanted to say thank you for creating a PR- by all means, keep changes coming!

The referenced commit was adding `git mf` to do the `merge --no-ff` in adamwhittingham/adshell, the successor to this bash-config (works for bash and zsh)

Thanks again for the PR, I hope to see more!

**Comment by MSadir** [comment]
Haha yeah Anna mentioned how happy you would be that I had created a PR. If I think of anything else I'll do the same thing again!

**Pull request closed without merging**
